# Sa-Token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: Authorization
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false
  # 是否尝试从cookie里读取token
  is-read-cookie: false
  # 是否从header中读取token
  is-read-header: true
  # 是否从body中读取token
  # token前缀
  token-prefix: Bearer
  # jwt秘钥
  jwt-secret-key: abcdefghijklmnopqrstuvwxyz
  # 是否尝试从请求体里读取token
  is-read-body: false
  # 是否在初始化配置时打印版本字符画
  is-print: false