server:
  port: 8002
spring:
  application:
    name: xunzhi-agent-admin
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
xunfei:
  appsecret: OGZkZGQ5ZDY0Yzc4MTllZWI3ZmU2MDU4
  appkey: e8565c438f59b301616e0498a86ad95d
  appflow: 7332665061114077184
  app-id: "your_app_id"
  api-key: "your_api_key"
  api-secret: "your_api_secret"
  rta-api-key: "your_rta_key"

xunzhi-agent:
  flow-limit:
    enable: true
    time-window: 1
    max-access-count: 20
