server:
  port: 8002

spring:
  application:
    name: short-link-admin
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
#      password: 123456
xunfei:
  appid: 5d0d0a0f
  appkey: 0d0d0a0f-0d0d-0d0d-0d0d-0d0d0d0d0d0d

short-link:
  flow-limit:
    enable: true
    time-window: 1
    max-access-count: 20
